// src/features/calendar/calendarService.test.ts
import { describe, expect, it, vi } from 'vitest';

import type { GeneratedDatePlan } from '@/types/domain';

vi.mock('expo-calendar', () => ({
  EntityTypes: { EVENT: 'event' },
  getCalendars: vi.fn(),
  requestCalendarPermissions: vi.fn(),
}));

vi.mock('expo-clipboard', () => ({
  setStringAsync: vi.fn(),
}));

vi.mock('react-native', () => ({
  Platform: { OS: 'ios' },
}));

vi.mock('@/lib/supabase', () => ({
  requireSupabaseClient: vi.fn(),
}));

import { buildCalendarEventNotes, buildCopyablePlan } from './calendarService';

const samplePlan: GeneratedDatePlan = {
  backupPlan: 'Keep the same ritual, but shorten it to one step.',
  calendarDescription: 'Calendar description generated by the deck.',
  calendarTitle: 'Date Night: Blanket Fort Broadcast',
  conversationPrompt: 'What has felt easy between us lately?',
  energy: 'low',
  estimatedBudgetLabel: 'Low cost',
  estimatedDurationMinutes: 105,
  foodPlan: 'Plan for a snack, small shared plate, or a non-food pause.',
  locationMode: 'at_home',
  premise: 'Turn the living room into a tiny low-pressure broadcast booth.',
  prepItems: ['Queue a playlist', 'Clear a cozy surface'],
  seed: 'blanket-fort:seed',
  shareTeaser: 'Tonight has a cozy card waiting.',
  sourceTemplateId: 'blanket-fort-broadcast',
  steps: [
    {
      description: 'Set up a warm corner without overthinking it.',
      durationMinutes: 30,
      id: 'step-1',
      sortOrder: 1,
      title: 'Set the scene',
    },
    {
      description: 'Trade tiny interviews about the week.',
      durationMinutes: 75,
      id: 'step-2',
      sortOrder: 2,
      title: 'Main event',
    },
  ],
  title: 'Blanket Fort Broadcast',
  twist: 'Add a one-song intermission chosen by each person.',
  vibeTags: ['cozy', 'low_energy'],
};

describe('calendar formatting helpers', () => {
  it('formats calendar notes with itinerary, prep, food, twist, and backup sections', () => {
    const notes = buildCalendarEventNotes(samplePlan);

    expect(notes).toContain(samplePlan.premise);
    expect(notes).toContain('Itinerary');
    expect(notes).toContain('1. Set the scene (30 min)\nSet up a warm corner without overthinking it.');
    expect(notes).toContain('2. Main event (1 hr 15 min)\nTrade tiny interviews about the week.');
    expect(notes).toContain('Prep list\n- Queue a playlist\n- Clear a cozy surface');
    expect(notes).toContain(`Food plan\n${samplePlan.foodPlan}`);
    expect(notes).toContain(`Twist\n${samplePlan.twist}`);
    expect(notes).toContain(`Backup plan\n${samplePlan.backupPlan}`);
  });

  it('prefixes copied calendar text with the editable calendar title', () => {
    const copyablePlan = buildCopyablePlan(samplePlan);

    expect(copyablePlan).toMatch(/^Date Night: Blanket Fort Broadcast\n\n/);
    expect(copyablePlan).toContain('Itinerary');
  });
});
